# PINN Temporal Graph Learning Configuration (Unsupervised)

# Model Architecture
model:
  n_nodes: 100  # Will be set to number of samples in data
  node_dim: 16
  n_eigengenes: 5  # Will be inferred from data

# Training Parameters
training:
  n_epochs: 1000
  batch_size: 32  # Not used in unsupervised setting
  learning_rate: 0.001
  weight_decay: 0.00001
  patience: 50
  min_delta: 1e-4

# Loss Weights
loss_weights:
  reconstruction: 1.0      # MSE between predicted and true eigengenes
  physics: 1.0            # Derivative consistency between network and graph
  tree: 0.01              # Tree structure constraint (reduced for sparse graphs)
  sign_consistency: 0.1    # Sign consistency along paths
  sparsity: 0.001         # Sparsity constraint (further reduced to allow edges)

# Data Parameters
data:
  n_samples: 100
  noise_level: 0.1
  period: 24.0

# Graph Constraints
graph:
  alpha: 1.0      # Tree structure weight (edge count)
  beta: 0.1       # Connectivity weight (Laplacian eigenvalue)
  max_path_length: 10

# Experiment Settings
experiment:
  name: "unsupervised_pinn_graph"
  save_dir: "experiments"
  log_interval: 50
  save_checkpoints: true
  plot_results: true